#DAY 21
#PRACTICE
#1.Create a CTE to calculate service statistics, then query from it. 
WITH SERVICE_STATISTICS AS(
SELECT UPPER (SERVICE) AS SERVICE,
       SUM(PATIENTS_ADMITTED)  AS TOTAL_ADMITTED,
       SUM(PATIENTS_REFUSED) AS TOTAL_REFUSED,
	   ROUND(AVG(PATIENT_SATISFACTION),2) AS AVG_SATISFACTION
FROM SERVICES_WEEKLY
GROUP BY SERVICE)
SELECT *
FROM SERVICE_STATISTICS
WHERE TOTAL_ADMITTED > 1500 
      AND TOTAL_REFUSED < 2000 
	  AND AVG_SATISFACTION > 75;
      
#2.Use multiple CTEs to break down a complex query into logical steps.
WITH X AS(
SELECT SERVICE, 
	   SUM(PATIENTS_ADMITTED) AS TOTAL_ADMITTED
FROM SERVICES_WEEKLY
GROUP BY SERVICE),
Y AS (
SELECT SERVICE, 
       ROUND(AVG(PATIENT_SATISFACTION),2) AS AVG_SATISFACTION
FROM SERVICES_WEEKLY
GROUP BY SERVICE)
SELECT UPPER(X.SERVICE) AS SERVICE,
	   TOTAL_ADMITTED, 
       AVG_SATISFACTION
FROM X
JOIN Y
ON X.SERVICE=Y.SERVICE
WHERE TOTAL_ADMITTED > 1500 AND AVG_sATISFACTION > 75;

#3.Build a CTE for staff utilization and join it with patient data.
WITH X AS (SELECT STAFF_ID,
	   STAFF_NAME,
       ROLE,
       SERVICE
FROM STAFF
WHERE ROLE IN ("DOCTOR", "NURSE"))
SELECT *
FROM PATIENTS P
JOIN X
ON X.SERVICE = P.SERVICE;

#DAILY CHALLENGE 
/* Create a comprehensive hospital performance dashboard using CTEs. Calculate: 1) Service-level metrics (total admissions, refusals, avg satisfaction), 2) 
Staff metrics per service (total staff, avg weeks present), 3) Patient demographics per service (avg age, count). 
Then combine all three CTEs to create a final report showing service name, all calculated metrics, and an overall performance score 
(weighted average of admission rate and satisfaction). Order by performance score descending.*/

WITH SERVICE_METRICS AS 
(SELECT SERVICE,
       SUM(PATIENTS_ADMITTED)  AS TOTAL_ADMITTED,
       SUM(PATIENTS_REFUSED) AS TOTAL_REFUSED,
	   ROUND(AVG(PATIENT_SATISFACTION),2) AS AVG_SATISFACTION
FROM SERVICES_WEEKLY
GROUP BY SERVICE) ,

STAFF_METRICS AS (
SELECT SERVICE, 
	   COUNT(DISTINCT STAFF_ID) AS TOTAL_STAFF,
       ROUND(SUM(CASE WHEN PRESENT=1 THEN 1 ELSE 0 END) * 1.0 / COUNT(DISTINCT STAFF_ID),2)  AS AVG_WEEKS_PRESENT
FROM STAFF_SCHEDULE
GROUP BY SERVICE),

PATIENT_METRICS AS 
(SELECT SERVICE,
       ROUND(AVG(AGE),0) AS AVG_AGE,
       COUNT(*) AS TOTAL_PATIENTS
FROM PATIENTS
GROUP BY SERVICE)

SELECT UPPER(X.SERVICE) AS SERVICE,
	   TOTAL_PATIENTS,
	   TOTAL_ADMITTED,
       TOTAL_REFUSED,
       AVG_AGE,
       TOTAL_STAFF,
	   AVG_SATISFACTION,
       AVG_WEEKS_PRESENT,
	   ROUND(
        (0.5 * (X.TOTAL_ADMITTED * 1.0 / (X.TOTAL_ADMITTED + X.TOTAL_REFUSED))
		+ 0.5 * (X.AVG_SATISFACTION / 100.0)),3) AS PERFORMANCE_SCORE
FROM SERVICE_METRICS X
JOIN STAFF_METRICS Y
ON X.SERVICE = Y.SERVICE
JOIN PATIENT_METRICS AS Z
ON Y.SERVICE = Z.SERVICE;
       
       