#1.Identify where and when the crime happened
SELECT EMPLOYEE_ID,
	   ROOM,
       DATE_FORMAT(ENTRY_TIME,'%H:%i:%s') AS ENTRY_TIME
FROM KEYCARD_LOGS
WHERE ROOM = "CEO OFFICE" 
ORDER BY ENTRY_TIME ASC;

#2.Analyze who accessed critical areas at the time
SELECT E.EMPLOYEE_ID,
       E.NAME,
       K.ROOM,
	   A.CLAIMED_LOCATION,
       DATE_FORMAT(K.ENTRY_TIME,'%H:%i:%s') AS ENTRY_TIME,
       DATE_FORMAT(K.EXIT_TIME,'%H:%i:%s') AS EXIT_TIME,
	   DATE_FORMAT(A.CLAIM_TIME,'%H:%i:%s') AS CLAIM_TIME
FROM EMPLOYEES E
JOIN KEYCARD_LOGS K 
ON K.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN ALIBIS A 
ON A.EMPLOYEE_ID = K.EMPLOYEE_ID
WHERE ROOM <> CLAIMED_LOCATION
AND ROOM = "CEO OFFICE"
AND EXIT_TIME LIKE "%21:00:00%" ;

#3.Cross-check alibis with actual logs
SELECT K.EMPLOYEE_ID,
       E.NAME,
       E.DEPARTMENT,
       K.ROOM,
       A.CLAIMED_LOCATION,
       IF (ROOM != CLAIMED_LOCATION, "Negative", "Positive") AS ANALYSIS
FROM KEYCARD_LOGS K
INNER JOIN ALIBIS A
ON A.EMPLOYEE_ID = K.EMPLOYEE_ID
INNER JOIN EMPLOYEES E
ON E.EMPLOYEE_ID = A.EMPLOYEE_ID
ORDER BY ANALYSIS ASC;
       
#4.Investigate suspicious calls made around the time
SELECT E.EMPLOYEE_ID,
       E.NAME,
       C.CALLER_ID,
       C.RECEIVER_ID,
	   DATE_FORMAT(C.CALL_TIME,'%H:%i:%s') AS CALL_TIME,
       C.DURATION_SEC
FROM CALLS C
INNER JOIN EMPLOYEES E
ON E.EMPLOYEE_ID = C.CALLER_ID
HAVING CALL_TIME BETWEEN "20:30:00" AND "21:10:00";

#5.Match evidence with movements and claims       
SELECT K.EMPLOYEE_ID,
       E.NAME,
       K.ROOM,
       A.CLAIMED_LOCATION,
       IF(K.ROOM <> A.CLAIMED_LOCATION AND K.ENTRY_TIME BETWEEN '2025-10-15 20:00:00' AND '2025-10-15 21:00:00',  "Killer", "Innocent") AS ANALYSIS
FROM ALIBIS A
INNER JOIN KEYCARD_LOGS K
ON K.EMPLOYEE_ID = A.EMPLOYEE_ID
INNER JOIN EMPLOYEES E
ON E.EMPLOYEE_ID = K.EMPLOYEE_ID
HAVING ANALYSIS = "KILLER";

